// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/blog/v1/blog.proto

package blogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_proto_blog_v1_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_v1_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_proto_blog_v1_blog_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blog) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type BlogId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogId) Reset() {
	*x = BlogId{}
	mi := &file_proto_blog_v1_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogId) ProtoMessage() {}

func (x *BlogId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_v1_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogId.ProtoReflect.Descriptor instead.
func (*BlogId) Descriptor() ([]byte, []int) {
	return file_proto_blog_v1_blog_proto_rawDescGZIP(), []int{1}
}

func (x *BlogId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_blog_v1_blog_proto protoreflect.FileDescriptor

const file_proto_blog_v1_blog_proto_rawDesc = "" +
	"\n" +
	"\x18proto/blog/v1/blog.proto\x12\ablog.v1\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\x04Blog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x18\n" +
	"\x06BlogId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x93\x02\n" +
	"\vBlogService\x12.\n" +
	"\n" +
	"CreateBlog\x12\r.blog.v1.Blog\x1a\x0f.blog.v1.BlogId\"\x00\x12,\n" +
	"\bReadBlog\x12\x0f.blog.v1.BlogId\x1a\r.blog.v1.Blog\"\x00\x125\n" +
	"\n" +
	"UpdateBlog\x12\r.blog.v1.Blog\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\tListBlogs\x12\x16.google.protobuf.Empty\x1a\r.blog.v1.Blog\"\x000\x01\x127\n" +
	"\n" +
	"DeleteBlog\x12\x0f.blog.v1.BlogId\x1a\x16.google.protobuf.Empty\"\x00B5Z3github.com/geekilx/grpc-course/proto/blog/v1;blogv1b\x06proto3"

var (
	file_proto_blog_v1_blog_proto_rawDescOnce sync.Once
	file_proto_blog_v1_blog_proto_rawDescData []byte
)

func file_proto_blog_v1_blog_proto_rawDescGZIP() []byte {
	file_proto_blog_v1_blog_proto_rawDescOnce.Do(func() {
		file_proto_blog_v1_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blog_v1_blog_proto_rawDesc), len(file_proto_blog_v1_blog_proto_rawDesc)))
	})
	return file_proto_blog_v1_blog_proto_rawDescData
}

var file_proto_blog_v1_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_blog_v1_blog_proto_goTypes = []any{
	(*Blog)(nil),          // 0: blog.v1.Blog
	(*BlogId)(nil),        // 1: blog.v1.BlogId
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_blog_v1_blog_proto_depIdxs = []int32{
	0, // 0: blog.v1.BlogService.CreateBlog:input_type -> blog.v1.Blog
	1, // 1: blog.v1.BlogService.ReadBlog:input_type -> blog.v1.BlogId
	0, // 2: blog.v1.BlogService.UpdateBlog:input_type -> blog.v1.Blog
	2, // 3: blog.v1.BlogService.ListBlogs:input_type -> google.protobuf.Empty
	1, // 4: blog.v1.BlogService.DeleteBlog:input_type -> blog.v1.BlogId
	1, // 5: blog.v1.BlogService.CreateBlog:output_type -> blog.v1.BlogId
	0, // 6: blog.v1.BlogService.ReadBlog:output_type -> blog.v1.Blog
	2, // 7: blog.v1.BlogService.UpdateBlog:output_type -> google.protobuf.Empty
	0, // 8: blog.v1.BlogService.ListBlogs:output_type -> blog.v1.Blog
	2, // 9: blog.v1.BlogService.DeleteBlog:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_blog_v1_blog_proto_init() }
func file_proto_blog_v1_blog_proto_init() {
	if File_proto_blog_v1_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blog_v1_blog_proto_rawDesc), len(file_proto_blog_v1_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blog_v1_blog_proto_goTypes,
		DependencyIndexes: file_proto_blog_v1_blog_proto_depIdxs,
		MessageInfos:      file_proto_blog_v1_blog_proto_msgTypes,
	}.Build()
	File_proto_blog_v1_blog_proto = out.File
	file_proto_blog_v1_blog_proto_goTypes = nil
	file_proto_blog_v1_blog_proto_depIdxs = nil
}
