FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.io,direct
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/blog-server ./blog/server

FROM scratch

COPY --from=builder /app/blog-server .
COPY --from=builder /app/grpc-cets ./grpc-cets

EXPOSE 50051

CMD ["./blog-server"]
