// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/calculator/v1/calculator.proto

package calculatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimeRequest) Reset() {
	*x = PrimeRequest{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeRequest) ProtoMessage() {}

func (x *PrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeRequest.ProtoReflect.Descriptor instead.
func (*PrimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

type PrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimeResponse) Reset() {
	*x = PrimeResponse{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeResponse) ProtoMessage() {}

func (x *PrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeResponse.ProtoReflect.Descriptor instead.
func (*PrimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *SumRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SumRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *SumResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type AvgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float32                `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgRequest) Reset() {
	*x = AvgRequest{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgRequest) ProtoMessage() {}

func (x *AvgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgRequest.ProtoReflect.Descriptor instead.
func (*AvgRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *AvgRequest) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

type AvgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvgResponse) Reset() {
	*x = AvgResponse{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgResponse) ProtoMessage() {}

func (x *AvgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgResponse.ProtoReflect.Descriptor instead.
func (*AvgResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{5}
}

func (x *AvgResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MaxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxRequest) Reset() {
	*x = MaxRequest{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxRequest) ProtoMessage() {}

func (x *MaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxRequest.ProtoReflect.Descriptor instead.
func (*MaxRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{6}
}

func (x *MaxRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type MaxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxResponse) Reset() {
	*x = MaxResponse{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxResponse) ProtoMessage() {}

func (x *MaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxResponse.ProtoReflect.Descriptor instead.
func (*MaxResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{7}
}

func (x *MaxResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_calculator_v1_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"$proto/calculator/v1/calculator.proto\x12\rcalculator.v1\"\x1c\n" +
	"\fPrimeRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\"'\n" +
	"\rPrimeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"(\n" +
	"\n" +
	"SumRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"%\n" +
	"\vSumResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"\x1a\n" +
	"\n" +
	"AvgRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x02R\x01a\"%\n" +
	"\vAvgResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"\x1e\n" +
	"\n" +
	"MaxRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\"%\n" +
	"\vMaxResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\x99\x02\n" +
	"\x11CalculatorService\x12D\n" +
	"\x05Prime\x12\x1b.calculator.v1.PrimeRequest\x1a\x1c.calculator.v1.PrimeResponse0\x01\x12<\n" +
	"\x03Sum\x12\x19.calculator.v1.SumRequest\x1a\x1a.calculator.v1.SumResponse\x12>\n" +
	"\x03Avg\x12\x19.calculator.v1.AvgRequest\x1a\x1a.calculator.v1.AvgResponse(\x01\x12@\n" +
	"\x03Max\x12\x19.calculator.v1.MaxRequest\x1a\x1a.calculator.v1.MaxResponse(\x010\x01B=Z;github.com/ilx/grpc-course/proto/calculator/v1;calculatorv1b\x06proto3"

var (
	file_proto_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_v1_calculator_proto_rawDescData []byte
)

func file_proto_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_v1_calculator_proto_rawDesc), len(file_proto_calculator_v1_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_v1_calculator_proto_rawDescData
}

var file_proto_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_calculator_v1_calculator_proto_goTypes = []any{
	(*PrimeRequest)(nil),  // 0: calculator.v1.PrimeRequest
	(*PrimeResponse)(nil), // 1: calculator.v1.PrimeResponse
	(*SumRequest)(nil),    // 2: calculator.v1.SumRequest
	(*SumResponse)(nil),   // 3: calculator.v1.SumResponse
	(*AvgRequest)(nil),    // 4: calculator.v1.AvgRequest
	(*AvgResponse)(nil),   // 5: calculator.v1.AvgResponse
	(*MaxRequest)(nil),    // 6: calculator.v1.MaxRequest
	(*MaxResponse)(nil),   // 7: calculator.v1.MaxResponse
}
var file_proto_calculator_v1_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.v1.CalculatorService.Prime:input_type -> calculator.v1.PrimeRequest
	2, // 1: calculator.v1.CalculatorService.Sum:input_type -> calculator.v1.SumRequest
	4, // 2: calculator.v1.CalculatorService.Avg:input_type -> calculator.v1.AvgRequest
	6, // 3: calculator.v1.CalculatorService.Max:input_type -> calculator.v1.MaxRequest
	1, // 4: calculator.v1.CalculatorService.Prime:output_type -> calculator.v1.PrimeResponse
	3, // 5: calculator.v1.CalculatorService.Sum:output_type -> calculator.v1.SumResponse
	5, // 6: calculator.v1.CalculatorService.Avg:output_type -> calculator.v1.AvgResponse
	7, // 7: calculator.v1.CalculatorService.Max:output_type -> calculator.v1.MaxResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_calculator_v1_calculator_proto_init() }
func file_proto_calculator_v1_calculator_proto_init() {
	if File_proto_calculator_v1_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_v1_calculator_proto_rawDesc), len(file_proto_calculator_v1_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_v1_calculator_proto_depIdxs,
		MessageInfos:      file_proto_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_v1_calculator_proto = out.File
	file_proto_calculator_v1_calculator_proto_goTypes = nil
	file_proto_calculator_v1_calculator_proto_depIdxs = nil
}
