// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/calculator/v1/calculator.proto

package calculatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimeRequest) Reset() {
	*x = PrimeRequest{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeRequest) ProtoMessage() {}

func (x *PrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeRequest.ProtoReflect.Descriptor instead.
func (*PrimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

type PrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimeResponse) Reset() {
	*x = PrimeResponse{}
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeResponse) ProtoMessage() {}

func (x *PrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeResponse.ProtoReflect.Descriptor instead.
func (*PrimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_calculator_v1_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"$proto/calculator/v1/calculator.proto\x12\rcalculator.v1\"\x1c\n" +
	"\fPrimeRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\"'\n" +
	"\rPrimeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2Y\n" +
	"\x11CalculatorService\x12D\n" +
	"\x05Prime\x12\x1b.calculator.v1.PrimeRequest\x1a\x1c.calculator.v1.PrimeResponse0\x01B=Z;github.com/ilx/grpc-course/proto/calculator/v1;calculatorv1b\x06proto3"

var (
	file_proto_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_v1_calculator_proto_rawDescData []byte
)

func file_proto_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_v1_calculator_proto_rawDesc), len(file_proto_calculator_v1_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_v1_calculator_proto_rawDescData
}

var file_proto_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_calculator_v1_calculator_proto_goTypes = []any{
	(*PrimeRequest)(nil),  // 0: calculator.v1.PrimeRequest
	(*PrimeResponse)(nil), // 1: calculator.v1.PrimeResponse
}
var file_proto_calculator_v1_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.v1.CalculatorService.Prime:input_type -> calculator.v1.PrimeRequest
	1, // 1: calculator.v1.CalculatorService.Prime:output_type -> calculator.v1.PrimeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_calculator_v1_calculator_proto_init() }
func file_proto_calculator_v1_calculator_proto_init() {
	if File_proto_calculator_v1_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_v1_calculator_proto_rawDesc), len(file_proto_calculator_v1_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_v1_calculator_proto_depIdxs,
		MessageInfos:      file_proto_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_v1_calculator_proto = out.File
	file_proto_calculator_v1_calculator_proto_goTypes = nil
	file_proto_calculator_v1_calculator_proto_depIdxs = nil
}
